//++++++++++++++++++++++++++++++start+++++++++++++++++++++++++++++++++++++++++++
#ifndef _APP_DISPLAY_H
#define _APP_DISPLAY_H
//------------------------------E N D-------------------------------------------

/*****************************************************************************
显示地址定义*/
//屏保界面
#define REG_SCREEN_SAVER_CO2_NUMBER						0x5a02
#define REG_SCREEN_SAVER_PM25_NUMBER					0x5a04
#define REG_SCREEN_SAVER_HUMIDITY						0x5a06
#define REG_SCREEN_SAVER_TEMP							0x2005//测量温度
//更多信息温度
#define REG_MORE_INWIND_TEMP							0x5a0A
#define REG_MORE_LOW_TEMP								0x5a0C
#define REG_MORE_HIGH_TEMP								0x5a0E
//主界面
#define REG_MASTER_CONTROL_DIS_HUMIDITY					0x5a00
#define REG_MASTER_CONTROL_DIS_MODE						0x2000//模式
#define REG_MASTER_CONTROL_DIS_WINDSPEDD				0x2002//风速
#define REG_MASTER_CONTROL_DIS_WINDSTATUS				0x2001//状态
#define REG_MASTER_CONTROL_DIS_TEMPSET				    0x2007//设定温度
#define REG_MASTER_CONTROL_DIS_HUMIDITYSET				0x2009//设定湿度
#define REG_MASTER_CONTROL_DIS_WINDSPEDD_GREEN			0x5c02
#define REG_MASTER_CONTROL_DIS_TIMING					0x5d00
#define REG_MASTER_CONTROL_DIS_SETTING					0x5e00
#define REG_MASTER_CONTROL_DIS_POWEROFF					0x5f00
#define REG_MASRER_CONTROL_DIS_HUMUDUTY_KEYT			0x6000
#define REG_MASRER_CONTROL_DIS_MODE_KEYT				0x6002

#define REG_MASTER_CONTROL_DIS_MODE_GREEN				0x5b02


#define REG_MASTER_WEEK_MONDAY							0x6102
#define REG_MASTER_WEEK_TUESDAY							0x6104
#define REG_MASTER_WEEK_WEDNESDAY						0x6106
#define REG_MASTER_WEEK_THURSDAY						0x6108
#define REG_MASTER_WEEK_FRIDAY							0x610a
#define REG_MASTER_WEEK_SATURDAY						0x610c
#define REG_MASTER_WEEK_SUNDAY							0x610e


#define REG_ERROR_BIT0									0x6A00
#define REG_ERROR_BIT1									0x6A02
#define REG_ERROR_BIT2									0x6A04
#define REG_ERROR_BIT3									0x6A06
#define REG_ERROR_BIT4									0x6A08
#define REG_ERROR_BIT5									0x6A0A
#define REG_ERROR_BIT6									0x6A0C
#define REG_ERROR_BIT7									0x6A0E
#define REG_ERROR_BIT8									0x6A10
#define REG_ERROR_BIT9									0x6A12
#define REG_ERROR_BIT10									0x6A14
#define REG_ERROR_BIT11									0x6A16
#define REG_ERROR_BIT12									0x6A18
#define REG_ERROR_BIT13									0x6A1A
#define REG_ERROR_BIT14									0x6A1C
#define REG_ERROR_BIT15									0x6A1E

//动态圆切图
#define REG_DYNAMIC_CIRCULAR_ADRESS						0x6B00//动态圆切图
//环控机
#define REG_ELECTRIC_HEATING_ADRESS						0x6B01//输出1
#define REG_FRE_ADRESS									0x6B02//输出2
#define REG_BYPASS_ADRESS								0x6B03
#define REG_REC_ADRESS									0x6B04
#define REG_BACK_FANSPEED_ERROR_ADRESS					0x6B05
#define REG_WENSHIDU_ERROE_ADRESS						0x6B06
//固定显示
#define REG_FREQ_CHAR_DIS_ADRESS						0x6B07
#define REG_FRE_SPEED_DIS_ADRESS						0x6B08
#define REG_REC_SPEED_DIS_ADRESS						0x6B09

#define REG_FREQ_CHAR									0x6B0A
#define REG_FRE_SPEED_NUMBER_ADRESS						0x6B0B
#define REG_REC_SPEED_NUMBER_ADRESS						0x6B0C

#define REG_FANSET_MOTOR_TYPE_ADRESS					0x6DD1
#define REG_FANSET_HIGHSPEED_ADRESS						0x6DD8
#define REG_FANSET_MIDPEED_ADRESS						0x6DDE
#define REG_FANSET_LOWSPEED_ADRESS						0x6DE4


#define REG_DEBUG_AC									0x6B36
#define REG_DEBUG_FAN									0x6B38
#define REG_DEBUG_FRE									0x6B3A
#define REG_DEBUG_REC									0x6B3C
#define REG_DEBUG_LOW_PRESS_PROTECT						0x6B3E
#define REG_DEBUG_TISHUIBENG_PROTECT					0x6B40
#define REG_DEBUG_HUASHUANG_PROTECT						0x6B42
#define REG_DEBUG_DUCT_SENSOR_ERROR						0x6B44
#define REG_DEBUG_HIGH_SENSOR_ERROR						0x6B46
#define REG_DEBUG_INTO_TEMP_ERROR						0x6B48
#define REG_DEBUG_WENSHIDU_ERROR						0x6B4A
#define REG_DEBUG_INTOWIND_TEMP_PROTECT					0x6B4C
#define REG_DEBUG_OUT_WATER_ERROR						0x6B4E

#define REG_TIME_CONTROL_WEEK_BASE						0x6B50
#define REG_TIME_CONTROL_WEEK_1							0x6B50
#define REG_TIME_CONTROL_WEEK_2							0x6B52
#define REG_TIME_CONTROL_WEEK_3							0x6B54
#define REG_TIME_CONTROL_WEEK_4							0x6B56
#define REG_TIME_CONTROL_WEEK_5							0x6B58
#define REG_TIME_CONTROL_WEEK_6							0x6B5A
#define REG_TIME_CONTROL_WEEK_7							0x6B5C
#define REG_TIME_CONTROL_TIME_1							0x6B5E
#define REG_TIME_CONTROL_TIME_2							0x6B60
#define REG_TIME_CONTROL_TIME_3							0x6B62
#define REG_TIME_CONTROL_TIME_4							0x6B64
#define REG_TIME_CONTROL_TIME_5							0x6B66
#define REG_TIME_CONTROL_TIME_6							0x6B68
#define REG_TIME_CONTROL_TIME_7							0x6B6A
//星期选中绿条
#define REG_DIS_WEEK_ADRESS 							0x6B6B
//星期显示 7*7
#define REG_TIME_CONTROL_WEEK_1_NUMBER1					0x6B6C
#define REG_TIME_CONTROL_WEEK_1_NUMBER2					0x6B6E
#define REG_TIME_CONTROL_WEEK_1_NUMBER3					0x6B70
#define REG_TIME_CONTROL_WEEK_1_NUMBER4					0x6B72
#define REG_TIME_CONTROL_WEEK_1_NUMBER5					0x6B74
#define REG_TIME_CONTROL_WEEK_1_NUMBER6					0x6B76
#define REG_TIME_CONTROL_WEEK_1_NUMBER7					0x6B78

#define REG_TIME_CONTROL_WEEK_2_NUMBER1					0x6B7A
#define REG_TIME_CONTROL_WEEK_2_NUMBER2					0x6B7C
#define REG_TIME_CONTROL_WEEK_2_NUMBER3					0x6B7E
#define REG_TIME_CONTROL_WEEK_2_NUMBER4					0x6B80
#define REG_TIME_CONTROL_WEEK_2_NUMBER5					0x6B82
#define REG_TIME_CONTROL_WEEK_2_NUMBER6					0x6B84
#define REG_TIME_CONTROL_WEEK_2_NUMBER7					0x6B86

#define REG_TIME_CONTROL_WEEK_3_NUMBER1					0x6B88
#define REG_TIME_CONTROL_WEEK_3_NUMBER2					0x6B8A
#define REG_TIME_CONTROL_WEEK_3_NUMBER3					0x6B8C
#define REG_TIME_CONTROL_WEEK_3_NUMBER4					0x6B8E
#define REG_TIME_CONTROL_WEEK_3_NUMBER5					0x6B90
#define REG_TIME_CONTROL_WEEK_3_NUMBER6					0x6B92
#define REG_TIME_CONTROL_WEEK_3_NUMBER7					0x6B94

#define REG_TIME_CONTROL_WEEK_4_NUMBER1					0x6B96
#define REG_TIME_CONTROL_WEEK_4_NUMBER2					0x6B98
#define REG_TIME_CONTROL_WEEK_4_NUMBER3					0x6B9A
#define REG_TIME_CONTROL_WEEK_4_NUMBER4					0x6B9C
#define REG_TIME_CONTROL_WEEK_4_NUMBER5					0x6B9E
#define REG_TIME_CONTROL_WEEK_4_NUMBER6					0x6BA0
#define REG_TIME_CONTROL_WEEK_4_NUMBER7					0x6BA2

#define REG_TIME_CONTROL_WEEK_5_NUMBER1					0x6BA4
#define REG_TIME_CONTROL_WEEK_5_NUMBER2					0x6BA6
#define REG_TIME_CONTROL_WEEK_5_NUMBER3					0x6BA8
#define REG_TIME_CONTROL_WEEK_5_NUMBER4					0x6BAA
#define REG_TIME_CONTROL_WEEK_5_NUMBER5					0x6BAC
#define REG_TIME_CONTROL_WEEK_5_NUMBER6					0x6BAE
#define REG_TIME_CONTROL_WEEK_5_NUMBER7					0x6BB0

#define REG_TIME_CONTROL_WEEK_6_NUMBER1					0x6BB2
#define REG_TIME_CONTROL_WEEK_6_NUMBER2					0x6BB4
#define REG_TIME_CONTROL_WEEK_6_NUMBER3					0x6BB6
#define REG_TIME_CONTROL_WEEK_6_NUMBER4					0x6BB8
#define REG_TIME_CONTROL_WEEK_6_NUMBER5					0x6BBA
#define REG_TIME_CONTROL_WEEK_6_NUMBER6					0x6BBC
#define REG_TIME_CONTROL_WEEK_6_NUMBER7					0x6BBE

#define REG_TIME_CONTROL_WEEK_7_NUMBER1					0x6BC0
#define REG_TIME_CONTROL_WEEK_7_NUMBER2					0x6BC2
#define REG_TIME_CONTROL_WEEK_7_NUMBER3					0x6BC4
#define REG_TIME_CONTROL_WEEK_7_NUMBER4					0x6BC6
#define REG_TIME_CONTROL_WEEK_7_NUMBER5					0x6BC8
#define REG_TIME_CONTROL_WEEK_7_NUMBER6					0x6BCA
#define REG_TIME_CONTROL_WEEK_7_NUMBER7					0x6BCC

#define REG_FAULT_COMMUNICATION							0x6BD0
#define REG_FAULT_HIGH_NTC								0x6BD2
#define REG_FAULT_LOW_NTC								0x6BD4
#define REG_FAULT_OUT_WATCH								0x6BD6
#define REG_FAULT_WENSHIDU								0x6BD8
#define REG_FAULT_INWIND_NTC							0x6BDA
#define REG_FAULT_LOW_PRESS_PROTECT						0x6BDC


#define REG_MORE_KEY_MESSAGE							0x6BDE
 
#define REG_MORE_PROTECE_MESSAGE						0x6BE0
#define REG_MORE_FAULT_MESSAGE							0x6BE2
#define REG_MORE_STATE_MESSAGE							0x6BE4

#define REG_MORE_DEF_PROTECE_MESSAGE					0x6BE6
#define REG_MORE_LOW_PRESSURE_PROTECE_MESSAGE			0x6BE8
#define REG_MORE_INWIND_TEMP_PROTECE__MESSAGE			0x6BEA
#define REG_MORE_HIGH_TEMP_PROTECE_MESSAGE				0x6BEC
#define REG_MORE_LOW_PRESSURE_WARNING_PROTECE_MESSAGE	0x6BEE

#define REG_MORE_INWIND_SENSOR_FAULT_MESSAGE			0x6BF0
#define REG_MORE_LOWTEMP_SENSOR_FAULT_MESSAGE			0x6BF2
#define REG_MORE_WENSHIDU_SENSOR_FAULT_MESSAGE			0x6BF4
#define REG_MORE_HIGH_SENSOR_FAULT_MESSAGE				0x6BF6
#define REG_MORE_OUTWATCH_SENSOR_FAULT_MESSAGE			0x6BF8

#define REG_MORE_REC_STATE_MESSAGE						0x6BFA
#define REG_MORE_FRE_STATE_MESSAGE						0x6BFC
#define REG_MORE_LIFT_WATCH_STATE_MESSAGE				0x6BFE
#define REG_MORE_WATCH_HEIGHT_STATE_MESSAGE				0x6C00
#define REG_MORE_AC_STATE_MESSAGE						0x6C02
#define REG_MORE_LOW_PRESSURE_STATE_MESSAGE				0x6C04

#define REG_MORE_INWIND_TEMP_ADRESS						0x6C06	
#define REG_MORE_LOWTEMP_TEMP_ADRESS					0x6C08
#define REG_MORE_HIGHTEMP_TEMP_ADRESS					0x6C0A		
#define REG_MORE_JUMP_ADRESS							0x6C0C

//时间设置起始地址
#define REG_MORE_YEARS_UP_ADRESS						0x6D00	
#define REG_MORE_YEARS_ADRESS							0x6D02
#define REG_MORE_YEARS_DOWN_ADRESS						0x6D04

#define REG_MORE_MONTH_UP_TEN_ADRESS					0x6D05	
#define REG_MORE_MONTH_UP_ADRESS						0x6D06	
#define REG_MORE_MONTH_TEN_ADRESS						0x6D07
#define REG_MORE_MONTH_ADRESS							0x6D08
#define REG_MORE_MONTH_DOWN_TEN_ADRESS					0x6D09
#define REG_MORE_MONTH_DOWN_ADRESS						0x6D0A

#define REG_MORE_DAY_UP_TEN_ADRESS						0x6D0B
#define REG_MORE_DAY_UP_ADRESS							0x6D0C
#define REG_MORE_DAY_TEN_ADRESS							0x6D0D
#define REG_MORE_DAY_ADRESS								0x6D0E
#define REG_MORE_DAY_DOWN_TEN_ADRESS					0x6D0F
#define REG_MORE_DAY_DOWN_ADRESS						0x6D10

#define REG_MORE_HOURS_UP_TEN_ADRESS					0x6D11
#define REG_MORE_HOURS_UP_ADRESS						0x6D12
#define REG_MORE_HOURS_TEN_ADRESS						0x6D13
#define REG_MORE_HOURS_ADRESS							0x6D14
#define REG_MORE_HOURS_DOWN_TEN_ADRESS					0x6D15
#define REG_MORE_HOURS_DOWN_ADRESS						0x6D16
#define REG_MORE_MINUTE_UP_TEN_ADRESS					0x6D17
#define REG_MORE_MINUTE_UP_ADRESS						0x6D18
#define REG_MORE_MINUTE_TEN_ADRESS						0x6D19
#define REG_MORE_MINUTE_ADRESS							0x6D1A
#define REG_MORE_MINUTE_DOWN_TEN_ADRESS					0x6D1B
#define REG_MORE_MINUTE_DOWN_ADRESS						0x6D1C
//机器码显示					0x6D1D		0x6D1E
//

//屏保低中高风速切图
#define REG_GREEN_LOW_WINDSPEED_ADRESS					0x6D20
#define REG_GREEN_MID_WINDSPEED_ADRESS					0x6D22
#define REG_GREEN_HIGH_WINDSPEED_ADRESS					0x6D24

//rtc 数字符号地址
#define REG_RTC_YEAR_ADRESS								0x6D26
#define REG_RTC_MONTH_TEN_ADRESS						0x6D28//月十位
#define REG_RTC_MONTH_ADRESS							0x6D2A
#define REG_RTC_DAY_TEN_ADRESS							0x6D2C
#define REG_RTC_DAY_ADRESS								0x6D2E
#define REG_RTC_HOUR_TEN_ADRESS							0x6D30
#define REG_RTC_HOUR_ADRESS								0x6D32
#define REG_RTC_MIN_TEN_ADRESS							0x6D34
#define REG_RTC_MIN_ADRESS								0x6D36

#define REG_RTC_CHAR1_ADRESS							0x6D38
#define REG_RTC_CHAR2_ADRESS							0x6D3A
#define REG_RTC_CHAR3_ADRESS							0x6D3C

//时段编辑开关机时间显示地址
#define REG_TIMECONTROL_POWERON_UP_TEN_ADRESS			0x6D40
#define REG_TIMECONTROL_POWERON_UP_ADRESS				0x6D41
#define REG_TIMECONTROL_POWERON_NOW_TEN_ADRESS			0x6D42
#define REG_TIMECONTROL_POWERON_NOW_ADRESS				0x6D43
#define REG_TIMECONTROL_POWERON_DOWN_TEN_ADRESS			0x6D44
#define REG_TIMECONTROL_POWERON_DOWN_ADRESS				0x6D45
#define REG_TIMECONTROL_POWEROFF_UP_TEN_ADRESS			0x6D46
#define REG_TIMECONTROL_POWEROFF_UP_ADRESS				0x6D47
#define REG_TIMECONTROL_POWEROFF_NOW_TEN_ADRESS			0x6D48
#define REG_TIMECONTROL_POWEROFF_NOW_ADRESS				0x6D49
#define REG_TIMECONTROL_POWEROFF_DOWN_TEN_ADRESS		0x6D4A
#define REG_TIMECONTROL_POWEROFF_DOWN_ADRESS			0x6D4B

#define MODE_ADRESS				0x5005
#define HUMIDITY_ADRESS			0x5006

//上位机动态显示的图片地址可能需要独立出来
//20201021
//地址 + 当前页 + 偏移 直接由宏定义完成，定义一个二维数组确定所有的显示变量。数组等待
#define DIS_NUMBER										10//暂定10，后续实例化确定数据量后在更改


#define REG_DIS_NUMBER_ADRESS							0x6000
#define REG_DIS_NUMBER_OFFSET							0

#define REG_DIS_PAGENUMBER_PAGE_29						25//页面切换还未做，临时测试下实例程序


typedef enum
{
	
	GREEN_SAVER,
	MAIN_CONTROL,
	SETING_1,
	SETING_2,
	SETING_3,
	SETING_4,
	SETING_5,
	SETING_6
}sys_state_t;//确认当前状态，决定更新哪些数据。各各数据段的起始地址需要规划

typedef struct
{
	uint16_t sys_state;
	uint16_t dis_adress;
	uint16_t dis_dat;
	uint16_t offset_dis_dat;
}disdata_t;
//++++++++++++++++++++++++++++++start+++++++++++++++++++++++++++++++++++++++++++
//Task
//名称: app_dis_sacnTask
//功能: 显示扫描
//入口: 无
//出口: 无
void app_display_scanTask(void);

//------------------------------E N D-------------------------------------------


#endif



